apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - image: harbor.apps.gdambor.com/library/petclinic:b7.20201016.194053
        name: petclinic
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: petclinic
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: petclinic-ingress
  namespace: default
spec:
  rules:
  - host: petclinic.apps.gdambor.com
    http:
      paths:
      - backend:
          serviceName: petclinic-svc
          servicePort: 80
